name: Claude Assistant
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write  # Required for OIDC authentication

jobs:
  claude-response:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for Claude
      
      - uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          max_turns: "10"  # Limit conversation turns
          timeout_minutes: 30
          custom_instructions: |
            You are working on the Project-You monorepo migration.
            Follow the CLAUDE.md file for project-specific guidance.
            Always test your changes before marking tasks complete.
            Use Bun instead of Yarn/npm for all operations.
            When making changes, ensure compatibility across iOS, Android, and Web platforms.
            Follow the migration plan in IMPLEMENTATION_PLAN.md.
            Update IMPLEMENTATION_TRACKING.md after completing tasks.